#!/bin/bash
set -e -x

. ./scripts/version

mkdir -p overlay/var/lib/rancher/k3s/agent/images
output_file="overlay/var/lib/rancher/k3s/agent/images/harvester-airgap-images-${ARCH}.tar"
if [ ! -f $output_file ]; then
  airgap_image_file='scripts/image-list.txt'
  images=$(cat "${airgap_image_file}")
  xargs -n1 docker pull <<< "${images}"
  docker save ${images} -o ${output_file}
fi