#!/bin/bash
set -e -x


cd $(dirname $0)/..

HARVESTER_VERSION=master

#harvester chart
#git clone --branch ${HARVESTER_VERSION} https://github.com/rancher/harvester.git /tmp/harvester
#helm package /tmp/harvester/deploy/charts/harvester -d ${BASE_PATH}/server/static/charts

#console
#git clone https://github.com/gitlawr/console.git $GOPATH/src/github.com/gitlawr/console
#GO111MODULE=off go build -o overlay/sbin/harvester-console $GOPATH/src/github.com/gitlawr/console/main.go


output_file="images/70-iso/harvester-images.tar"
if [ ! -f $output_file.zst ]; then
  airgap_image_file='scripts/image-list.txt'
  images=$(cat "${airgap_image_file}")
  xargs -n1 docker pull <<< "${images}"
  docker save ${images} -o ${output_file}

  zstd --rm ${output_file} -o ${output_file}.zst
fi